// Ui options
export const UI_HAMBURGER_CLICKED = 'HAMBURGER_CLICKED'
export const UI_REGISTER_CLICKED = 'REGISTER_CLICKED'
export const UI_LOGIN_BACK_CLICKED = 'LOGIN_BACK'


// table user 
export const TABLE_USER_SEARCH = 'TABLE_USER_SEARCH'
export const TABLE_USER_INITDATA = 'TABLE_USER_INITDATA'
export const TABLE_USER_SUCESS = 'TABLE_USER_SUCESS'
export const TABLE_USER_FAIL = 'TABLE_USER_FAIL'

// transaction data
export const TABLE_TRANSACTION_SEARCH = 'SEARCH'
export const TABLE_TRANSACTION_INITDATA = 'TABLE_TRANSACTION_INITDATA'
export const TABLE_TRANSACTION_SUCESS = 'TABLE_TRANSACTION_SUCESS'
export const TABLE_TRANSACTION_FAIL = 'TABLE_TRANSACTION_FAIL'

// login data
export const LOGIN_USER_USERNAME = 'LOGIN_USER_USERNAME'
export const LOGIN_USER_PASSWORD = 'LOGIN_USER_PASSWORD'
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"



// value user input in user action
export const USER_DEPOSIT_VALUE = 'DEPOSIT_VALUE'
export const USER_WITHDRAW_VALUE ='WITHDRAW_VALUE'
export const USER_TRANSFER_VALUE = 'TRANSFER_VALUE'
export const USER_TRANSFER_ID = 'USER_TRANSFER_ID'

// value input button
export const USER_DEPOSIT_VALUE_BUTTON = 'DEPOSIT_VALUE_BUTTON'
export const USER_WITHDRAW_VALUE_BUTTON ='WITHDRAW_VALUE_BUTTON'
export const USER_TRANSFER_VALUE_BUTTON = 'TRANSFER_VALUE_BUTTON'

